describe('Home page flow', ()=> {
    beforeEach(()=> {
        cy.intercept('GET', 'http://localhost:3001/api/v1/urls', { fixture: 'mock_data_1.json' })
        cy.visit('http://localhost:3000')
    })
    it('Should be able to visist the app and render the correct elements', ()=> {
        cy.contains('URL Shortener')
            .get('form')
            .get('div')
                .should('have.class', 'url')
            .get('h3')
                .contains('Awesome photo')
            .get('a')
                .contains("http://localhost:3001/useshorturl/1")
            .get('p')
                .contains('https://images.unsplash.com/photo-1531898418865-480b7090470f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80')
                .get('div')
                .should('have.class', 'url')
            .get('h3')
                .contains('Awesome photo 2')
            .get('a')
                .contains('http://localhost:3001/useshorturl/2')
            .get('p')
                .contains('https://images.unsplash.com/photo-1470114716159-e389f8712fda?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80')
    })
    it('Should be able to visist the app and view the form with the proper inputs', ()=> {
        cy.get('form [name="title"]').first()
            .get('input').first()
                .invoke('attr', 'placeholder')
                .should('contain', 'Title...')
            .get('form [name="title"]').first()
            .get('input').next()
                .invoke('attr', 'placeholder')
                .should('contain', 'URL to Shorten...')
            .get('button')
                .contains('Shorten Please!')
    })
    it('Should be able to fill out the form and render the correct information in the input fields', ()=> {
        cy.get('form').then(($form) => {
            cy.contains('URL Shortener')
                .get('form [name="title"]').first()
                    .type('Mountain photo')
                .get('input').first()
                    .invoke('attr', 'value')
                    .should('contain', 'Mountain photo')
                .get('form [name="urlToShorten"]')
                    .type('https://media.istockphoto.com/photos/aerial-view-of-misty-mountains-at-sunrise-picture-id1195458582?k=20&m=1195458582&s=612x612&w=0&h=gzpAJTwppTIEAhNbUaHnjuRQoYon0F4C87UQ3xXv1oU=')
                .get('input').next()
                    .invoke('attr', 'value')
                    .should('contain', 'https://media.istockphoto.com/photos/aerial-view-of-misty-mountains-at-sunrise-picture-id1195458582?k=20&m=1195458582&s=612x612&w=0&h=gzpAJTwppTIEAhNbUaHnjuRQoYon0F4C87UQ3xXv1oU=')
        })
    })
})